CONTRIBUTING.md, Caddyfile, backend/backend/settings.py
This is a small PR for enforcing the usage of SSL even in localhost, this helped me foresee an issue regarding  CSRF and its usage with SSL, if a domain with https isn't included in `settings.py`, CSRF protection won't work : 
```json
{ 
"detail": "CSRF Failed: Origin checking failed - https://zane.local does not match any trusted origins."
}
```
Since we want to enforce CSRF for the users who will install this app, we want to make sure that it will work as expected for them.
=> ♻️ use SSL for localhost

backend/zane_api/services.py, backend/zane_api/tests/docker.py, backend/zane_api/tests/project.py, backend/zane_api/views/docker.py, backend/zane_api/views/projects.py
This pull request is mostly cleanup job, I wanted to move from classes to functions because I didn't want to instantiate the `DockerService` manually on each call, and I have noticed that I made all methods classmethods while they really don't have any need for it to be like that. 
```bash
make openapi # will generate OpenAPI schema at `/openapi/schema.yaml`
make freeze # will update the `requirements.txt` file if you added new packages
```
```bash
```
=> :recycle: Use functions instead of classes for services

backend/zane_api/services.py, backend/zane_api/tests/project.py
This small PR is for adding labels to resources so that outside they are marked as managed by zaneops.
```bash
make openapi # will generate OpenAPI schema at `/openapi/schema.yaml`
make freeze # will update the `requirements.txt` file if you added new packages
```
```bash
```
=> :recycle: Add resource labels on project

frontend/src/components/nav-link.tsx, frontend/src/components/tailwind-indicator.tsx, frontend/src/routes/__root.tsx
This adds a new component `<TailwindIndicator />` for debugging the current breakpoint and screen width. 
https://github.com/Fredkiss3/zane-ops/assets/38298743/432bc691-f082-41e4-b9e7-5e8503900a6a
> [!NOTE]  
> I also moved the `<NavLink>` component into its own file, it shouldn't be in the same place as the root layout.
=> Feat/add tailwind indicator component 

frontend/tsconfig.json
This is a small PR to force TS to always import types with `import type`. 
```bash
cd backend
```
```bash
```
=> 🔧 Use typescript verbatim to enforce importing types with `import type`

backend/backend/settings.py, backend/package.json, backend/requirements.txt, backend/zane_api/tests/auth.py, backend/zane_api/views/auth.py
This PR removes the usage of `django-ratelimit` with Django Rest Framework throttling, the response returned by DRF is way more actionable than what `django-ratelimit` gives us and allows us to show messages like this one : 
I also added the ratelimit to all endpoints for unauthenticated users by default as an another security firewall.
closes #68 
```bash
cd backend
```
```bash
```
=> :recycle: Use default Django Rest Framework throttling for ratelimiting

backend/backend/api_description.py, backend/backend/settings.py, backend/requirements.txt, backend/zane_api/serializers.py, backend/zane_api/tests/auth.py, backend/zane_api/tests/base.py, backend/zane_api/tests/docker.py, backend/zane_api/tests/project.py, backend/zane_api/tests/service.py, backend/zane_api/tests/volume.py, backend/zane_api/views/__init__.py, backend/zane_api/views/auth.py, backend/zane_api/views/base.py, backend/zane_api/views/docker.py, backend/zane_api/views/docker_services.py, backend/zane_api/views/domain.py, backend/zane_api/views/projects.py, backend/zane_api/views/volume.py, frontend/src/api/v1.ts, frontend/src/lib/utils.ts, frontend/src/routes/login.lazy.tsx, frontend/tsconfig.json, openapi/schema.yml
This PR involves replacing our custom serializers for error responses and instead this will allow us to instead send a standard error form that supports nested children
closes #73
```bash
cd backend
```
```bash
```
=> ♻️  Use DRF Standardized Errors for errors returned by the API

CONTRIBUTING.md, backend/backend/settings.py, backend/zane_api/tests/service.py, backend/zane_api/views/docker_services.py, docker/build-push-caddy-image.sh, docker/dnsmasq/dnsmasq.conf, docker/docker-compose.yaml, docker/proxy/Dockerfile, docker/start-docker-stack.sh, reset-db.sh
This Pull Request adds a local DNS server for resolving zaneops domains, the benefit of this approach is the so that all  `*.zaneops.local` domains will points to `localhost` and we won't need to manually add entries to our localhost for them to work, It also allows us to better replicate the production behavior.  
This PR also changes the domain where the app is served from from `zane.local` to `app.zaneops.local`. 
> [!IMPORTANT]
> This is a pretty big change in how the DEV server is setup, so please follow the instructions [here](https://github.com/zane-ops/zane-ops/pull/85/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R90-R105) to update your local setup, I only included instructions for MacOs only, if you don't use macOS, please reach out to us to update …
=> :recycle: Use a local DNS server for resolving domain names & replace default domain with `app.zaneops.local`

backend/backend/settings.py, backend/zane_api/docker_operations.py, backend/zane_api/tests/base.py, docker/docker-stack.yaml
This small PR makes calling the proxy service more reliable by using labels instead of calling the proxy service by name, this is so that we can call the service another name or since we will use docker-stack in production, the service name is not guaranteed to be the same.
```bash
cd backend
```
```bash
```
=> :recycle: Use a label for getting the `zane_proxy` service instead of calling the service by name

backend/backend/settings.py, backend/zane_api/tests/auth.py, backend/zane_api/views/auth.py, frontend/src/components/helper/use-auth-user.tsx, openapi/schema.yml
By default Django keep the session for 2 weeks without renewing it,  in this PR  we add the ability to extend the session for connected users when they request the user data from the client, if there is only less than 2 days left, the app will try to keep them connected for 7 more days.
I also added the code to keep refreshing the session on the client each 30 minutes to not loose the connection state.
```bash
cd backend
```
```bash
```
=> :passport_control: Extend session if less than 2 days left and still logged-in

backend/zane_api/tests/base.py, backend/zane_api/tests/deployment.py, backend/zane_api/tests/docker.py, backend/zane_api/tests/project.py, backend/zane_api/tests/service.py, backend/zane_api/tests/volume.py
This PR refactors the tests so that patched modules are always patched and we don't need to repeat ourselves everywhere
```bash
cd backend
```
```bash
```
=> :recycle: Centralize always patched modules

backend/backend/settings.py, backend/zane_api/views/base.py, openapi/schema.yml
This PR fixes an error with drf_spectacular marking fields that are not specified as read only in serializers as optional, even though they are always provided. 
Solution kindly provided by : https://github.com/tfranzel/drf-spectacular/issues/480#issuecomment-898488288
```bash
cd backend
```
```bash
```
=> :memo: fix bad API spec generation considering non read_only fields as optional

backend/zane_api/tests/deployment.py, backend/zane_api/views/docker_services.py
This PR fixes a bug with the previous one, we forgot to check for existing project & service
```bash
cd backend
```
```bash
```
=> :bug: Check for non existing service & project

backend/zane_api/tests/deployment.py, backend/zane_api/urls.py, backend/zane_api/views/base.py, backend/zane_api/views/docker_services.py, backend/zane_api/views/helpers.py, backend/zane_api/views/projects.py, backend/zane_api/views/serializers.py, openapi/schema.yml
This PR builds on top of #106, this adds the ability to cancel pending changes.
```bash
cd backend
```
```bash
```
=> Feat: cancel pending deployment changes

backend/backend/settings.py, backend/zane_api/docker_operations.py, backend/zane_api/models/base.py, backend/zane_api/serializers.py, backend/zane_api/tasks.py, healthcheck-strategy.md
This adds the zero-downtime deployment story on caddy, we do this by reverse proxying to the blue & green deployments on caddy, each request is retried 3 times to assure that they are really dead.
```bash
cd backend
```
```bash
```
=> :sparkles: Added blue-green deployments on caddy to allow for zero-downtime deployments

backend/zane_api/docker_operations.py, backend/zane_api/models/base.py, backend/zane_api/serializers.py, backend/zane_api/tests/deployment.py, backend/zane_api/urls.py, backend/zane_api/views/docker_services.py, backend/zane_api/views/helpers.py, openapi/schema.yml
This is the last PR to finish #44, in this PR, we implement the ability to redeploy old deployments and bring state of the service to the one at the point of the chosen deployment.
closes #44
```bash
cd backend
```
```bash
```
=> Feat: Redeployments of previous deployments

CONTRIBUTING.md, Makefile, docker/attach-proxy-networks.sh, docker/docker-stack.yaml, docker/start-docker-stack.sh, docker/stop-docker-stack.sh
In this PR, I made some modifications about how we start and setup the dev server, as it made starting the DEV server flaky, with the new changes, the dev server should start without any issue now, I also updated the contribution docs to reflect the changes. 
Now to start the dev server, you need to run 2 commands instead of one : 
```shell
make dev
make dev-api
```
```bash
cd backend
```
```bash
```
=> Chore: Updated setup scripts and contributing docs

frontend/src/routes/__root.tsx, frontend/src/routes/_dashboard/project.$slug.tsx
Use `Link` components instead of `a` tag in 404 pages.
```bash
cd backend
```
```bash
```
=> 💄 use `Link` components instead of `a` tag in 404 pages

backend/zane_api/tests/logs.py, backend/zane_api/views/serializers.py
Since logs are saved as JSON values, `"` is escaped, so we need to do the same when searching for logs containing it.
```bash
cd backend
```
```bash
```
=> :bug: replace `"` with `\"` character when searching for content in logs

Makefile
This is a small fix for the Makefile, the `venv`s should be activated with either `.` or `source`, we can't just call the script directly. 
```bash
cd backend
```
```bash
```
=> 🔨 fix makefile

backend/zane_api/tasks.py, backend/zane_api/tests/deployment.py
In this PR I fixed a bug where when we update an URL for a service, the entry for the old url value is still kept in the proxy configuration. I found this bug in production 🤦🏾 .
```bash
cd backend
```
```bash
```
=> Fix: delete old url entries when modifying an URL

backend/zane_api/tasks.py, backend/zane_api/tests/logs.py
In this PR, we make it so that logs are deleted after archiving a service, as we don't need them anymore.  However to delete logs, we don't do it in the `archive` endpoint directly, but after deleting the service in docker within the worker, this is because the service might still be up and send logs if we delete it directly, we will need to make sure the service is down before deleting all the logs it could produce. 
```bash
cd backend
```
```bash
```
=> Fix: Delete all service logs after archiving a service

docs/Caddyfile, docs/src/components/Footer.astro
same as the title
```bash
cd backend
```
```bash
```
=> 🔧 use cache-control headers for assets and not for HTML for docs

.github/workflows/build-push-images-canary.yaml, .github/workflows/build-push-images-dev.yaml, backend/zane_api/docker_operations.py
I also found this bug in producton, when you deploy an app with a base_path like `/docs`, in the proxy it would match urls starting with `/docs/*` to your service, excluding `/docs` itself, this PR fixes that.
```bash
cd backend
```
```bash
```
=> Fix: URLs path matchers should not end with a `/` matcher

backend/zane_api/views/projects.py
There was a bug in the dashboard, when we create a service but do not deploy it yet, it would have the `image` field to `None` or we use it to display the image in the frontend, we need to instead get the image from the `change` created.
```bash
cd backend
```
```bash
```
=> 🐛 fix bug with service not created throwing an error due to `image` being `None`

backend/zane_api/docker_operations.py, backend/zane_api/tests/docker.py
Since we can't search images by tags, we don't need to add a tag suffix, I also removed the `library/` prefix from official repositories to reflect more what the docker hub API returns.
```bash
cd backend
```
```bash
```
=> ♻️ change API to not return images with `latest` tag and remove `library` prefix

frontend/src/lib/hooks/use-project-details.tsx, frontend/src/lib/hooks/use-project-list.tsx
10 seconds is too long and it takes a lot of time before the user can see if their service has deployed for ex, same for the statuses in the project list. 
```bash
cd backend
```
```bash
```
=> ♻️ use 5 seconds as the refetch interval for queries instead of 10

backend/zane_api/docker_operations.py
When searching for image `ghcr.io/zane-ops/docs`, zaneOps throw a 500 error, we catch it to not throw an error.
```bash
cd backend
```
```bash
```
=> 🐛 do not return 500 error on non existing image

README.md, docs/astro.config.mjs
In this PR, I added an official ROADMAP for zaneops containing the missing features for a beta version & then a v1 and eventually a v2.
I always hate writing these as they remind me of the tremendous amount of work that is left 😑 . 
Thankfully, if we finish the beta, the features for the V1 will reuse a lot of the code we wrote for docker services.
I also removed the `architecture` section in the docs for now as it would stay not written for long.
```bash
cd backend
```
```bash
```
=> 📝 add ROADMAP to beta, v1 & v2

backend/Dockerfile.prod, backend/backend/settings.py, backend/requirements.txt
I did this because I stumbled on a bug where the API would hang indefinitely, the fix was to remove daphne package, instead we will use gunicorn like before. 
```bash
cd backend
```
```bash
```
=> :heavy_minus_sign: Remove daphne & use gunicorn instead

docker/proxy/Dockerfile
In this PR, I changed the docker image for the proxy to use `caddy run --resume`, in prepration for the usage in github actions, since github action don't support commands.
```bash
cd backend
```
```bash
```
=> ♻️ Add command to proxy docker image

deploy.mk
This is necessary for temporal to work on production, the `default` namespace is not created by default, so we create it in the script that deploys the app.
```bash
cd backend
```
```bash
```
=> 🔨 Create default namespace & enable archival & visibility in temporal prod script

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/shared.py, backend/zane_api/temporal/workflows.py
This PR fixes some bugs : 
- Even if you scale down some services, there would still be some tasks for the service, tricking our jobs to think that the services were never scaled down, to fix it, we filter only by `desired-state: 'running'` to assure that only running tasks are up.
- The workflow would try to scale down and back previous failed deployments, which is not needed and they should already be down.
```bash
cd backend
```
```bash
```
=> Some deployment fixes

backend/backend/settings.py, docker/docker-compose.yaml, docker/docker-stack.prod.yaml
In this PR, we added a new concept named backend components, since the `backend` image will be reused for different things, this allows us to identify which component it is used for. 
As of now, we only have two components that use the backend image, the API and temporal worker, but in the future, there will also be the builder. 
This also allows us to not call the proxy to register the URLs of the API & front in `settings.py` for the other components, only the API is supposed to do that. 
```bash
cd backend
```
```bash
```
=> :recycle: separate backend images in specific components

backend/zane_api/temporal/activities.py, backend/zane_api/views/serializers.py, docker/docker-compose.yaml, openapi/schema.yml
This PR fixes a bug where deployment logs for services weren't saved in `DEV`, this is because when we moved from celery to temporalio, we exposed the temporal worker to `network_host` and we forgot to include `ZANE_FLUENTD_HOST` env variable, we assumed that the default value of `unix://$HOME/.fluentd/fluentd.sock` would automatically resolve the `$HOME` env variable to the correct value, but since the worker is run inside of a container, that is not the case. 
The fix is to pass the `$ZANE_FLUENTD_HOST` to the image from the outside, like we do in production.
In this PR, there is also some new features : 
- we modified the `logs` endpoint to allow filtering by one or multiple sources.
- we modified the `http-logs` endpoint to allow filtering by `request_id`
- we include the request id …
=> Fix/deployment logs not being saved in DEV

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/workflows.py
In this PR, we fixed a sneaky bug for when we have to remove old volumes created by previous deployments in the deployment process.  
Previously if a deployment failed it would not delete those volumes if the next deployment does not have changes of type `REMOVE` volumes  in them. 
Now, we only remove old deployment by comparing all the volumes to the volumes attached to the service and removing any that is not.  
There is also persistent annoying flaky tests that I tried to mitigate by being more lenient on the `wait_condition` in `DeployDockerServiceWorkflow`. 
```bash
cd backend
```
```bash
pnpm run format # format the files using …
```
=> :recycle: Do not use changes to remove old volumes

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/schedules/activities.py, backend/zane_api/temporal/schedules/workflows.py, backend/zane_api/temporal/workflows.py
As the title says, when the temporal-worker hasn't run a job in a long time, django might drop the database connections to them, to fix it, we close faulty db connections at the start of each job, this way django will need to recreate the connections next time it needs to make a DB query. 
```bash
cd backend
```
```bash
```
=> :bug: Fix bug with temporal jobs failing background jobs because the worker hasn't run in a long time and DB connections have been dropped

backend/.dockerignore, backend/Dockerfile, backend/Dockerfile.prod
To reduce the image size, the current image is more than `1GB` :
The new size is `~800mo`, I tried using `alpine` but it didn't seem to build correctly, some packages (notably temporalio), were not being installed correctly. 
```bash
cd backend
```
```bash
```
=> 🔧 use a smaller image size for building `backend` component

backend/zane_api/tests/deployment.py, backend/zane_api/views/docker_services.py
This fixes a bug we encountered when deleting all urls for a service which previously had ones alongside a healthcheck of type `PATH`, the temporal job would fail because that healthcheck expected the new deployment to have a URL but a deployment url was only generated when there was at least one URL attached to the service. 
To fix, we instead generate a deployment URL when there is a http port associated to a service.
```bash
cd backend
```
```bash
```
=> :recycle: New deployments should have a generated URL as long as there is a http port

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/workflows.py, backend/zane_api/tests/base.py, backend/zane_api/tests/deployment.py
This PR fixes an issue in which when the user updates a service and uses a nonexistent image, the deploy workflow times out, this is because we didn't handle when an image doesn't exists. Temporalio would retry the `create_swarm_service` activity and fail after hitting all the steps. 
To fix this, we separated the image pulling into its own activity and catched the error when the image doesn't exist. 
```bash
cd backend
```
```bash
```
=> Fix: pulling image should not timeout the deployment workflow

.github/workflows/pytests.yaml, backend/zane_api/temporal/workflows.py, backend/zane_api/tests/deployment.py
I don't actually know why tests sometimes don't work on CI then work again on the next commit, I get timeout errors suddenly and I actually don't know how to fix them. The tests will be re-enabled for CI, with a timeout of 5 minutes max instead of running indefinitely when they fail, to be sure. 
```bash
cd backend
```
```bash
```
=> 👷 re-enable and fix django tests on CI

backend/zane_api/temporal/activities.py
This fixes a bug when a user cancels a deployment, it would throw an error because we don't filter the changes by the correct type. 
```bash
cd backend
```
```bash
```
=> 🐛 specify change field of `urls` when cancelling a service.

backend/zane_api/temporal/activities.py, backend/zane_api/tests/deployment.py, backend/zane_api/views/projects.py
This PR fixes a bug on production where deployments which were stuck in the deploying step and weren't marked removed. This is because of a Bug that probably happenned in the temporal workflow step keeping them stuck.    
```bash
cd backend
```
```bash
```
=> fix: mark stuck deployments as `removed` when a new deployment is succesfull

backend/zane_api/temporal/activities.py, backend/zane_api/tests/deployment.py, backend/zane_api/views/docker_services.py, frontend/src/components/deployment-cards.tsx
In this PR, we fixed multiple issues :
- We made it so that only deployments that have not finished yet can be cancelled and if we already cancelled a previous deployment, the cancel request can be ignored.
- When we mark stuck deployments as `REMOVED`, we need to set the `started_at` and `finished_at` only if the corresponding property was null
- in the frontend, we fixed the deployment dropdown menu to show the `cancel` & `redeploy` on the correct states.
```bash
cd backend
```
```bash
```
=> Some fixes related to deployments

backend/zane_api/models/base.py, backend/zane_api/serializers.py, backend/zane_api/temporal/activities.py, openapi/schema.yml
This PR introduces the system environment variables in the API response to show in the UI, it was already done in the backend, but now it is sent to be shown in the frontend so that users are aware of that. 
```bash
cd backend
```
```bash
```
=> ✨ inject system env variables in zaneops

CONTRIBUTING.md, backend/backend/settings.py, docker/start-docker-stack.sh, docs/src/content/docs/development/development.mdx, frontend/vite.config.ts
This change is only for the development environment, instead of starting the dev server at `app.127-0-0-1.sslip.io`, we use the port where the frontend is running. This is because the dev server would cause a full reload when we deploy a new service which has at least one url. 
This is an issue with caddy (and not with vite), documented here https://github.com/caddyserver/caddy/issues/6420. Basically, for services which have urls, when we deploy them, we need to update the configuration of caddy, and when this configuration is updated, caddy closes all the websocket connections causing all clients to reconnect. This is not a big issue, but in DEV, vite will issue a full reload when the connection is closed. This was annoying too me, so I made it so that the DEV server for vite doesn't use …
=> 🔧  run the dev server at `http://localhost:5678` instead of the `sslip.io` domain

backend/zane_api/tests/deployment.py
This skips some tests that mark the CI as failed because they sometimes fail while they work normally locally. We don't want to delete them because they are essential to the app, but we don't need to check if we broke the CI because of them. 
```bash
cd backend
```
```bash
```
=> 🩹 skip cancel deployment tests in CI because they are flaky

backend/backend/settings.py, docs/src/content/docs/get-started.mdx
fix #239 
As said in the issue :
> This is caused by the fact that the url to use for local testing is not an URL that the user owns, so the certificate generated by the proxy (caddy) is not valid, when we the use http it doesn't work because we specified in the API that the session cookie should only work on https.
We fixed this by adding an environment variable that allow accessing zaneops through http even on production.
```bash
cd backend
```
```bash
```
=> 🩹 add env variable to allow logging in to zaneops via HTTP on production

Dockerfile.docs, docs/package.json, docs/src/pages/api-reference/openapi.astro
This will make it so that when we add or update an API endpoint, we do not need to redeploy the docs website.
```bash
cd backend
```
```bash
```
=> 📝 do not copy `openapi.yaml` file in the docs API reference

frontend/src/api/v1.ts, frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx
we add support for updating the slug in the UI, the experience is made to be seamless, the user will not notice that we redirected to a new page when changing the slug of the service.
```bash
cd backend
```
```bash
```
=> ✨ support updating the service slug in the UI

frontend/src/lib/hooks/use-cancel-docker-service-change-mutation.ts, frontend/src/lib/hooks/use-docker-service-single-query.ts, frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.lazy.tsx, frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx
In this PR we implemented the logic for updating the service image and credentials in the UI.
```bash
cd backend
```
```bash
```
=> feat: update service image and credentials

backend/zane_api/views/docker_services.py, frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx
In this PR, we added a little feedback for when a change is not possible to revert, the API would send the response but it wasn't shown in the UI, this PR adds that in form of a little toast.
We also changed the error messages in the backend a little to be more in line with the expressions we use in the frontend.
```bash
cd backend
```
```bash
```
=> refactor: show error message when a change is not feasible

frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx
same as the PR title.
```bash
cd backend
```
```bash
```
=> fix: when the change is empty show `<empty>` in the command input instead of the old value

backend/zane_api/tests/service.py, backend/zane_api/urls.py, backend/zane_api/views/docker_services.py, deploy.mk, docker/start-docker-stack.sh, docker/stop-docker-stack.sh
In this PR we fixed the bug where if we created projects or services with slugs containing underscores (`_`) or starting/ending with hyphens (`-`), the API would raise a 404 because it didn't match the regex we set for the routes, so to fix it we made the regex for the slugs used in the routes match the one from django. 
fixes #246 
```bash
cd backend
```
```bash
```
=> 🐛 fix URLs not matching the slug regex of django

README.md, backend/zane_api/temporal/activities.py, backend/zane_api/temporal/schedules/activities.py, backend/zane_api/temporal/shared.py, backend/zane_api/tests/base.py, backend/zane_api/tests/deployment.py, backend/zane_api/views/docker_services.py, deploy.mk, docker/start-docker-stack.sh, frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx
> This is to fix a bug with exposed ports conflicting with a new deployment, the new deployment creates a service that needs the ports of the service to be available, but it is still used by the old deployment. 
> To fix this we scale down and remove the ports from the old services
> and reattach the ports to the old service if the new deployment fails
fixes #263 
```bash
cd backend
```
```bash
```
=> fix: port conflict during redeployment by forcefully unbinding ports from old deployments

deploy.mk
The command `grep -q <word>` matches partially, so `grep -q "active"` will match both `inactive` & `active`, to fix it we use `grep -qw <word>` to match exactly.
```bash
cd backend
```
```bash
```
=> 🔧 Fix typo in deploy makefile

frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/index.tsx
it looks like this : 
closes #292 
```bash
cd backend
```
```bash
```
=> feat: new `LIVE ⚡️` indicator

frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/index.tsx
Makes logs rendering more performant by removing the overscan of 25 logs to always load. This way if we have only two logs visible in the viewport with BIG ANSI texts, they won't affect the perf as much as if they were 25 (the default). 
It was causing performance issues because the `AnsiHtml` component would run a parsing of all the 25 big logs (which is not very fast), so to mitigate this, we only allow it to parse the logs visible logs. 
The 25 overscan value was an arbitrary number so that the scrolling would be smoother.
fixes #293 
```bash
cd backend
```
```bash
```
=> fix: logs rendering perf by removing tanstack virtual overscan

frontend/src/components/service-cards.tsx, frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/index.tsx
The CSS highlight API requires that your element can be selected, so the class that we used `select-none` which corresponds to the css : `user-select: none`, disabled it, making it not work as expected.
So the fix is to remove this class, and we can prevent selecting the invisible text by pushing it behind the visible text.
fix #291 
fix #300 
```bash
cd backend
```
```bash
```
=> fix: safari highlight not working 

.github/workflows/build-push-images-canary.yaml, .github/workflows/build-push-images-dev.yaml, deploy.mk, docker/proxy/Dockerfile, frontend/src/components/helper/auth-redirect.tsx
The bug was happening because we build the proxy image with the default config for the `dev` environment 🤦🏾 , to fix this with added the build-arg `ENVIRONMENT` variable and set it to `prod`
fixes #308 
We also included some other changes in this PR : 
- Changed the deploy script to generate a `sslip.io` subdomain with the IP of the server (if they are on Linux) 
- Fixed a bug with auth-redirect, we should not redirect to login
- we also moved from building the proxy image from scratch everytime to using a prebuilt image
- we added another command for deploying the app, by default it will execute in https-only, but you can deploy with `http` enabled, the backend will automatically restrict the ports open on caddy accordingly :
<br/>
```shell
make deploy-with-http
```
- But Moving from …
=> fix: Caddy not generating SSL certificates correctly

backend/backend/bootstrap.py, backend/backend/settings.py, backend/zane_api/tests/base.py, backend/zane_api/tests/logs.py, backend/zane_api/urls.py, backend/zane_api/views/base.py, backend/zane_api/views/logs.py, backend/zane_api/views/proxy.py, docker/docker-compose.yaml, docker/docker-stack.prod.yaml, docker/fluentd/fluent.conf, docker/proxy/default-caddy-config-dev.json, docker/proxy/default-caddy-config-prod.json, docker/start-docker-stack.sh
In this PR we added the ability for the API to automatically setup the TLS app on startup so that users would upgrade by just making another deploy. this way it mitigates the bug in #315 by not hardcoding that in the default json config.
closes #278 
We also added a way to secure internal endpoints : 
- The logs endpoint is secured with `Basic` authentication by providing the generated django secret key as the password, `fluentd` will use that automatically.
- I wanted to also secure the tls certificate check endpoint, but 1) it is not possible to pass the secret as headers or search params when configuring caddy 2) the endpoint is already rate-limited for anonymous users and only validates certificates for the ones that are actually needed
This PR require rerunning `make setup` for users …
=> refactor: auto-setup TLS app on proxy & secure internal endpoints

frontend/src/components/date-range-with-shortcuts.tsx, frontend/src/components/multi-select.tsx, frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/index.tsx
In this PR, we changed the design of the `multi-select` component to be more like shadcn one : 
_theirs_ :
_ours_ : 
We also change the `date-range-with-shortcut` component time to be relative to each time it is rerendered.
closes #305 
closes #306
> [!WARNING]
```bash
cd backend
```
```bash
```
=> refactor: some UI changes

frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/index.tsx
**Before** : 
**After** : 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> refactor: remove mix-blend-mode on highlighted logs

backend/backend/bootstrap.py, backend/zane_api/tests/logs.py
In this PR, we added the template configuration for `502` status which represents the status for when the service has been removed or has not yet started. We also updated the `404` template to be set on startup.
closes #277 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> feat: upload `404` & `502` error templates on startup

docker/docker-stack.prod.yaml
That is enough for the server to start.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> refactor: reduce the start grace period for the api to `10s`

backend/zane_api/dtos.py, backend/zane_api/temporal/workflows.py, backend/zane_api/tests/deployment.py
Services with only read only volumes don't need to be scaled down as it won't cause a corruption, so we don't need to cause downtime for them. 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> refactor: allow blue/green deployments for services with only `read-only` volumes

backend/backend/settings.py, backend/zane_api/migrations/0172_auto_20250118_0233.py, backend/zane_api/views/logs.py
There was a bug with the database migration code, in the migration code we get the IP of the request from the `X-Forwarded-For` header, by reading the JSON value of the `request_headers` field. However, the syntax of that header can have multiple values separated by commas (`,`) ([see syntax](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax)), the first value in the commas is the actual value of the client IP, so we modified the function to take it into account.
> [!WARNING]
```bash
cd backend
```
```bash
pnpm install --frozen-lockfile # Install the packages at …
```
=> fix: `X-Forwarded-For` header can have multiple IPs

backend/zane_api/views/docker_services.py, frontend/app/components/http-log-request-details.tsx, frontend/app/components/multi-select.tsx, frontend/app/components/ui/table.tsx, frontend/app/routes/deployments/deployment-http-logs.tsx, frontend/app/routes/services/service-http-logs.tsx
In this PR, we make some changes : 
- Modified the condition for filtering field values for the HTTP logs to use `icontains` 
- fixed text break in the UI for the details of HTTP logs
- added a style in the http log rows for when they are selected
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: some UI fixes regarding http logs

backend/zane_api/views/docker_services.py
Exactly as the title.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: Use `startswith` and limit results to `7`

backend/backend/bootstrap.py, backend/backend/settings.py, docker/docker-stack.prod.yaml
This a BUG fix regarding the proxy and elasticsearch, when tested on a production server, we noticed that : 
- Elasticsearch is killed by out of memory errors, as the resource limits where too close to the heap size in the config
- Fix proxy SSL error, the proxy uses `zane.front.zaneops.internal` 
---
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: allow all zaneops internal domains in the backend

docker/docker-stack.prod-http.yaml, docker/docker-stack.prod.yaml, docker/docker-stack.yaml
I ask deepseek and chatGPT and they gave me this solution, I don't understand it fully, but it seems to work 🤷🏾‍♂️ . From what I understand : 
> we can publish the ports using the `mode: host` and it will bypass docker load balancing, allowing us to get the real IP from the client.
Link to the chat discussion : 
> https://chatgpt.com/share/679e8694-b35c-8007-918b-fd3cb47a16cf
```shell
make setup
make deploy
```
> [!WARNING]
```bash
cd backend
```
```bash
pnpm run format # format the files using …
```
=> fix: proxy get the real IP instead of the client ip of `10.0.0.2`

backend/zane_api/views/projects.py, frontend/app/components/change-fields.tsx
When a project has a service that hasn't been deployed yet, it should get the image from the field `source` and not `image`.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: Bug with `project-list` endpoint for undeployed services

backend/zane_api/tests/project.py, backend/zane_api/views/projects.py
I missed something in #350 , `new_value` is a dict, not an object.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: `project/service-list` endpoint (Again)

backend/zane_api/management/commands/create_system_cleanup_schedule.py, backend/zane_api/temporal/activities.py, backend/zane_api/temporal/workflows.py
In the previous PR #349, we only removed dangling and unnamed volumes, this doesn't really do anything if you deploy & archive multiple services which leaves tagged but unused images, or volumes that are created outside of zaneops that are not used. this way we free up as much space as possible.
Of course, we prevent removing volumes used by services, as for images, if you put a service to sleep, its image will be cleaned up, but what is cool with docker services is that, they are self healing, when the service wakes up, it will pull the image again.
> [!WARNING]
```bash
cd backend
``` …
=> refactor: cleanup containers and volumes more aggressively

backend/zane_api/views/serializers.py
We added this rule so that it wouldn't prevent zero dowtime deployments, but honestly, the user is already warned in the frontend, so if they want to do it, we let them.
fixes #254 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: do not prevent creating other ports while a http port exists

Makefile, docker/docker-stack.prod.yaml
exactly as the title says. I also added commands for starting the temporal-ui server.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: restart policy for services as zane_app get stuck sometimes

docker/docker-compose.yaml, docker/docker-stack.prod.yaml, docker/docker-stack.yaml, docker/temporalio/admin-tools-entrypoint.sh
The temporal archival volume gets way too big after some time, and technically, we don't really use it, storing the archival data for workflows is not at all necessary. We also disabled the archival feature in `temporal-admin-tools` service.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: remove archival storage in temporal

backend/zane_api/temporal/activities.py
This was an issue I encountered when working trying to deploy https://github.com/solidtime-io/solidtime on zaneops, the default `solidtime` image has its own healthcheck. Since the image is reused by other components, we needed to override the healthcheck to adapt them to these services. However, zaneops didn't do that because we don't rely on docker's default healthcheck. To fix this, we just disable the default healthcheck of the service in favor of our own external healthcheck. I also changed the restart policy to restart on any state (even if the container was stopped succesfully) instead of restarting only on failure.
> [!WARNING]
```bash
cd backend
pnpm run freeze # …
```
=> fix: override `healthcheck` in service and relax restart policy

backend/requirements.txt, backend/zane_api/views/docker_services.py, backend/zane_api/views/serializers.py
The filters were not working at all, that was because we modified them to only take into account status filters instead of the other filters too.
We also deleted one unused package : `mypy-extension`
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: http logs filters

frontend/app/components/http-log-request-details.tsx
So we just use an array instead.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: `iterator.entries().map` isn't implemented in safari

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/workflows.py
Sometimes the previous deployment is not cleaned up, and we don't know why... this PR attemps to fix it.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: bug with previous deployment not cleaned up

backend/zane_api/temporal/schedules/activities.py
The monitoring health checks would run after a succesful deployment and override the status of the removed deployment which can be confusing.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: do not run monitoring healthcheck against non production deployments

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/schedules/activities.py, docker/docker-compose.yaml, frontend/app/components/http-log-request-details.tsx, frontend/app/components/service-changes-modal.tsx, frontend/app/components/ui/alert.tsx, frontend/app/components/ui/sheet.tsx, frontend/app/routes/layouts/service-layout.tsx, frontend/app/routes/projects/project-settings.tsx, frontend/app/routes/services/create-docker-service.tsx, frontend/app/routes/services/service-metrics.tsx, frontend/app/routes/services/settings/service-danger-zone-form.tsx, frontend/app/routes/services/toggle-service-state.tsx
In this PR we finally fixed the bug with metrics collection, when `blkio` is `None`, we should set the default value to empty array.
I also fixed a bug with the system collection job : we should not delete networks managed by zaneops. 
I also made some other UX changes in the UI : 
- added a confirmation dialog for when the user want to put service to sleep
> <img width="574" alt="Screenshot 2025-03-10 at 02 20 30" src="https://github.com/user-attachments/assets/60fcac7a-8f67-44a1-9a9c-3b5403a53355" />
- and more...
> [!WARNING]
```bash
cd backend
```
```bash
pnpm install --frozen-lockfile # …
```
=> fix: metrics collection workflow failing when disk I/O is None

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/schedules/activities.py
We didn't log errors when the service is stopped, and has no running tasks, so I fixed it. 
I also made it so that there isn't a max attempts of restarts when creating the service. 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: log unhealthy error when the service is down, and allow infinite restarts

frontend/app/components/ui/fieldset.tsx, frontend/app/components/ui/input.tsx, frontend/app/routes/layouts/service-layout.tsx, frontend/app/routes/services/settings/service-configs-form.tsx, frontend/app/routes/services/settings/service-healthcheck-form.tsx, frontend/app/routes/services/settings/service-ports-form.tsx, frontend/app/routes/services/settings/service-source-form.tsx, frontend/app/routes/services/settings/service-urls-form.tsx, frontend/app/routes/services/settings/service-volumes-form.tsx
In a recent change I made, the `deploy now` button would redirect incorrectly to a URL with `undefined` in it. So I fixed it.
In this PR, I also made it so that fields that required fields in the settings page are marqued correctly.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: redirect correctly when clicking `deploy now`

backend/zane_api/temporal/activities.py
This was difficult to figure out. 
- On production, sometimes, deploments would become unavailable after a certain, returning users `502` errors
- This was because of our load balancing policy which would send request to the old deployment which was already removed instead of sending the request to the current active deployment. 
- The bug is a combination of the load balancing policy which was `first` and the `fail_duration` which was of **30 seconds**. In the span of 30s, if caddy marked our new deployment as unavailable, it would not make any request to that new deployment and instead only make the request to the first upstream, which is referencing the old deployment that have already been cleaned up.
- We changed the policy from `first` to `round_robin`, this way caddy would at least …
=> fix: Occasional 502 Bad Gateway Error on server

frontend/app/routes/deployments/deployment-metrics.tsx, frontend/app/routes/services/service-metrics.tsx, frontend/app/routes/services/settings/service-resource-limits-form.tsx, frontend/app/utils.ts
This way, the user can easily see what are the values on the slder : 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> feat: show server limits on the settings page

backend/zane_api/temporal/activities.py, backend/zane_api/temporal/schedules/activities.py
This is the last PR for fixing the issue with occasional `502 Bad Gateway` errors. Instead of using load balancing with the blue and green deployment while one of them is down, we simply replace the previous deployment with the new deployment when updating the proxy configuration for the service in production.
In this PR, there are also some other changes : 
- Fixed a bug that sometimes arises in production with service metrics, data would become missing after a long time, this is because we would select the incorrect container for the service. it should only get the metrics of containers for tasks that should be running 
- Changed the health check logic to check for all success status codes, not only `200 OK`
> [!WARNING]
```bash
cd backend
pnpm …
```
=> refactor: simplify proxy configuration for blue/green deployments

frontend/app/routes/services/service-metrics.tsx
I noticed in production, that the CPUs percentage we show in the frontend is limited to 100% and the data can go over 100%, the over 100% is not a bad thing as it is proportional to the number of CPUs of the machine, so 300% out of 100% means 3 CPUs over for ex 4 CPUs :
So instead of limiting ourselves to 100%, we will show instead the number of CPUs used out of the whole  :
> [!WARNING]
```bash
cd backend
```
```bash
```
=> feat: show the percentage of CPU usage relative to the number of CPUs of the machine

backend/zane_api/urls.py
The webhook deploy URL regex wasn't correct, making it only work without a trailing slash. 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> 🐛 webhook deploy urls should accept an optional trailing slash 

backend/Dockerfile, backend/backend/settings.py, backend/zane_api/git_client.py, backend/zane_api/models/base.py, backend/zane_api/process.py, backend/zane_api/temporal/activities/git_activities.py, backend/zane_api/temporal/activities/main_activities.py, backend/zane_api/temporal/constants.py, backend/zane_api/temporal/helpers.py, backend/zane_api/temporal/shared.py, backend/zane_api/temporal/worker.py, backend/zane_api/temporal/workflows.py, backend/zane_api/tests/base.py, backend/zane_api/tests/changes.py, backend/zane_api/tests/git_service_builder.py, backend/zane_api/utils.py, backend/zane_api/views/docker_services.py, backend/zane_api/views/git_services.py, backend/zane_api/views/helpers.py, backend/zane_api/views/serializers.py, frontend/app/components/service-cards.tsx, frontend/app/routes/layouts/dashboard-layout.tsx, frontend/app/routes/layouts/deployment-layout.tsx
- Fixed this bug : https://github.com/zane-ops/zane-ops/issues/437#issuecomment-2797912613
- Fixed a bug with Git service cards not showing `FAILED` when a deployment is failed, instead it shows a green chip with no text inside of it
- Refactored out the common parts of the subprocess execution logic to a common class that is tasked to run the subprocess instead, this way it is reusable elsewhere
- Fix a bug with cancellation logic for deployments, previously the cancellation would cancel every queued & running deployment, now it only cancels the requested deployment
- The update toast is not showed if in PR branch version
- Fixed redeployments to only compute changes from the latest production deployment 
- We pass all envs generated by nixpacks to the `docker build` process now 
fixes …
=> fix: various bug fixes related to nixpacks builder

backend/zane_api/middleware.py, backend/zane_api/temporal/activities/main_activities.py, backend/zane_api/temporal/schedules/activities.py, backend/zane_api/tests/base.py, backend/zane_api/tests/networks.py, backend/zane_api/tests/service.py
This is in preparation for the future, using the container ID is much more precise that the deployment alias.
In the future, we will be able to use this for services with multiple replicas and be able to check of them individually.
I also added logs for commands and requests done by the healthchecks.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> refactor: use container id for healthchecks

frontend/app/routes/onboarding.tsx
Because we forgot to pass the `X-CSRFToken` header when calling the `/auth/create-initial-user` endpoint, new installs would not work and fail the creation of the first user.
What's strange is the fact that this error doesn't happen with `v1.10` even though we haven't modified the onboariding code since at least two versions prior. I may have modified something with the CSRF settings on the backend that would cause this error.
> [!WARNING]
```bash
cd backend
```
```bash
pnpm run format # format the files using …
```
=> fix: onboarding bug missing csrf header

backend/git_connectors/models.py, backend/git_connectors/views/gitlab.py
`/projects?owned=true` only returns repositories created by the current user. This limits the result to exclude repos you're a developer or a maintainer but not owner. We should use `membership=true` (which is used already) that returns all repositories that the user has any level of access (owner, maintainer, developer, reporter or guest). As expected, it doesn't include public repos you don't have a role in.
Follow up to #467 
Before: (only two projects)
After: should return all of these
> [!WARNING]
```bash
cd backend
```
```bash
pnpm install --frozen-lockfile # Install the packages at the exact version …
```
=> GitLab: Include all user-associated repositories, not only user-created ones

backend/git_connectors/tests/github_auto_deploy.py, backend/git_connectors/views/github.py, backend/git_connectors/views/gitlab.py, backend/zane_api/tests/base.py
The branch name can have `/` in it, so instead of splitting the ref by `/` we just get all the string after `ref/heads`
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: resolve the branch name correctly in the auto-deploy webhook

backend/zane_api/views/auto_update_docker_services.py
For performance reasons, instead of fetching the `/releases` API which returns the whole list of releases we instead call the API that get a single release directly. 
> [!WARNING]
```bash
cd backend
```
```bash
```
=> chore: Use API for getting single tag for the auto-update API

frontend/app/routes/services/create-service.tsx
The git provider option should be first as it is probably the most common option that users want. 
I also changed the icons.
| before | after |
| ------------ | ------------ |
| <img width="539" height="513" alt="image" src="https://github.com/user-attachments/assets/9b2b1fe2-bb69-4f36-8d90-efb222faa28f" />      | <img width="491" height="417" alt="Screenshot 2025-07-21 at 23 31 54" src="https://github.com/user-attachments/assets/c950c15f-1ea9-41f2-af4b-11dfe3e24b7c" />     |
> [!WARNING]
```bash
cd backend
```
```bash
pnpm install --frozen-lockfile # Install the packages at the exact version listed in the …
```
=> chore: change the order of links in new service page

frontend/app/lib/queries.ts, frontend/app/routes/layouts/dashboard-layout.tsx
The settings endpoint will throw if you are not authenticated, fixed it in this PR.
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: do not throw error for settings endpoint

frontend/app/routes/environments/environment-service-list.tsx, frontend/app/routes/services/components/service-urls-form.tsx, frontend/app/routes/services/services-env-variables.tsx
The spaces between those elements felt too tight.  
Also, the `.toArray` extension is [newly base-lined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/toArray#browser_compatibility). I had about an hour debugging a runtime error in service environment variables page until I figured out that my browser doesn't support it. If we’re OK with this level of bleeding edge let me know to revert it. I made it so no one passes what I had to
fixes #
| Before | After |
| ------------ | ------------ |
|  <img width="1920" height="1200" alt="Screenshot from 2025-09-10 18-41-02" src="https://github.com/user-attachments/assets/5e91c269-0359-4584-a6a7-11950c2c4b92" />   |<img width="1920" height="1200" alt="Screenshot from 2025-09-10 18-41-12" …
=> chore: more reliable spacing in services page when it's empty

backend/zane_api/models/archived.py, backend/zane_api/tests/preview_environments.py, backend/zane_api/views/git_services.py, backend/zane_api/views/projects.py
Reported by @AhmedBaset .
> [!WARNING]
```bash
cd backend
```
```bash
```
=> fix: prevent deleting all Preview metadata when closing PR 
