backend/backend/settings.py

fix: allow 127.0.0.1

---

.github/workflows/pytests.yaml
.github/workflows/tests.yaml
CONTRIBUTING.md
backend/backend/settings.py
backend/requirements.txt
backend/zane_api/tests.py
backend/zane_api/views.py

This Pull Request sets up the tests, the CI for the tests and adds authentication tests.

Chore/setup backend tests + authentication tests

---

.github/pull_request_template.md
CONTRIBUTING.md

Updated contributions docs and Pull Request template with more instructions for onboarding.

📝 Update contributing docs

---

backend/backend/settings.py
backend/requirements.txt

So that it looks nicer 🙃
```bash
make openapi # will generate OpenAPI schema at `/openapi/schema.yaml`
make freeze # will update the `requirements.txt` file if you added new packages
```

🔧 colorize the django test outpout

---

frontend/src/routes/login.lazy.tsx

fix: removed form pass infos to form.root

---

backend/zane_api/services.py
backend/zane_api/tests/volume.py
backend/zane_api/urls.py
backend/zane_api/views/__init__.py
backend/zane_api/views/volume.py
openapi/schema.yml

API endpoint to Get the usage size of a volume to show in the UI.
closes #39 
```bash
make openapi # will generate OpenAPI schema at `/openapi/schema.yaml`
make freeze # will update the `requirements.txt` file if you added new packages
```
```bash
```

Feat/Get Volume Size usage

---

docker/docker-compose.yaml

Network `zane-out` won't exist for everybody, so i removed it.
```bash
cd backend
```
```bash
```

🐛 fix inexistent docker network

---

frontend/src/api/v1.ts
frontend/src/key-factories.ts
frontend/src/routes/index.lazy.tsx
frontend/src/routes/login.lazy.tsx

Using Query Key factories.
Entries and functions that will produce query keys

feat: query keys initiated

---

frontend/index.html
frontend/src/components/logo.tsx
frontend/src/components/meta-title.tsx
frontend/src/lib/utils.ts
frontend/src/routes/__root.tsx
frontend/src/routes/login.lazy.tsx

closes #75
A not found implemented for routes that don't exist

feat: not found

---

CONTRIBUTING.md
Makefile

Make it easier to setup the project and reduce the number of commands we have to type to start the project, I also added instructions for the local DNS server in linux (ubuntu).
```bash
cd backend
```
```bash
```

:memo: Add simple setup script and update contribution docs

---

.github/workflows/scorecard.yml
README.md

introduce [openssf scorecard](https://securityscorecards.dev)
it's the default config ofter by [openSSF](https://openssf.org)
> [!NOTE]
> the score is likely to be low but easy to fix
Openssf scorecard is a tool that gives a security score for a project.
It will check a set of rules such as:
- the review of pr
- branch protection
- the presence of a licence 
...
But It's not analyse code such as if there are XSS ...
all this in order to give an overview of the security of the project for people arriving on it.

feat(openssf scorecard): introduce

---

frontend/src/key-factories.ts
frontend/src/lib/hooks/use-project-list.tsx
frontend/src/routes/_dashboard/index.lazy.tsx

THis pr is about the pagination

feat: pagination

---

frontend/package.json
frontend/src/components/ui/tooltip.tsx
frontend/src/key-factories.ts
frontend/src/lib/hooks/use-project-list.tsx
frontend/src/routes/_dashboard/index.lazy.tsx
pnpm-lock.yaml

This PR is about to implement the sorting

Dashboard sort

---

backend/zane_api/serializers.py
openapi/schema.yml

In this PR I included the description in the archived project endpoint. 
```bash
cd backend
```
```bash
```

include description in archived project endpoint

---

backend/zane_api/serializers.py
openapi/schema.yml

Include missing attribute `id` in `archived-projects/` endpoint
```bash
cd backend
```
```bash
```

include id in archived endpoint

---

frontend/package.json
frontend/src/api/v1.ts
frontend/src/components/ui/menubar.tsx
frontend/src/key-factories.ts
frontend/src/lib/hooks/use-project-list.tsx
frontend/src/routes/_dashboard/index.lazy.tsx
pnpm-lock.yaml

this Pr is about filtering by status

feat: status

---

frontend/src/components/status-badge.tsx

This adds an animation similar to the ping animation in the tailwind docs : https://tailwindcss.com/docs/animation#ping
Here is how it looks like : 
https://github.com/zane-ops/zane-ops/assets/38298743/cddbf595-e872-4a9f-b2ad-a8830cacdced
```bash
cd backend
```
```bash
```

💄 add live animation on status on dashboard

---

frontend/src/components/ui/button.tsx
frontend/src/components/ui/textarea.tsx
frontend/src/routes/_dashboard.tsx
frontend/src/routes/_dashboard/create-project.lazy.tsx
frontend/src/routes/_dashboard/index.lazy.tsx

Create project, worked just on the ui

feat: create project ui

---

frontend/package.json
frontend/src/api/client.ts
frontend/src/components/service-cards.tsx
frontend/src/components/ui/breadcrumb.tsx
frontend/src/components/ui/card.tsx
frontend/src/components/ui/separator.tsx
frontend/src/index.css
frontend/src/routes/_dashboard.tsx
frontend/src/routes/_dashboard/create-project.lazy.tsx
frontend/src/routes/_dashboard/index.lazy.tsx
frontend/src/routes/_dashboard/project.$slug.lazy.tsx
frontend/tailwind.config.js
pnpm-lock.yaml

This pr is about the poject details interface.
part of #137

feat: project details ui

---

frontend/src/routes/_dashboard/project.$slug.lazy.tsx

fix: removing the title service

---

deploy.mk
docker/docker-stack.prod.yaml
docs/deploying.md

Update instructions for the deployment instructions.
```bash
cd backend
```
```bash
```

:memo: updating instructions for deploying

---

deploy.mk
docs/deploying.md

This is some fixes again
```bash
cd backend
```
```bash
```

:memo: some fixes to the depoy instructions

---

.github/workflows/build-push-images-canary.yaml
.github/workflows/build-push-images-dev.yaml

```bash
cd backend
```
```bash
```

👷 add ci for building docs on main

---

Dockerfile.docs
docs/package.json

```bash
cd backend
```
```bash
```

♻️ use `start` instead of `dev` for production in the docs

---

frontend/src/components/service-cards.tsx
frontend/src/routes/_dashboard.lazy.tsx
frontend/src/routes/_dashboard/project.$slug.tsx

In the PR, I made some UI changes such as making the header sticky, making the URL in the service cards link correctly, and some other minor changes.  
```bash
cd backend
```
```bash
```

Refactor: UI changes

---

.github/workflows/build-push-images-dev.yaml
docs/src/pages/api-reference/openapi.astro

```bash
cd backend
```
```bash
```

📝 (docs): fix openapi page title & favicon

---

Dockerfile.docs

```bash
cd backend
```
```bash
```

🐛 Copy openapi reference to the correct file

---

frontend/tsconfig.json

This makes it so that, unused imports and variables won't fail the build.
```bash
cd backend
```
```bash
```

🔧  allow for unused locals & parameters in TS

---

frontend/package.json
frontend/src/components/ui/alert.tsx
frontend/src/components/ui/command.tsx
frontend/src/key-factories.ts
frontend/src/lib/hooks/use-search-docker-hub.tsx
frontend/src/routes/_dashboard/project_/$slug.create-service.lazy.tsx
frontend/src/routes/_dashboard/project_/$slug_.create-service.docker.lazy.tsx
frontend/src/routes/_dashboard/project_/$slug_.create-service.docker.tsx
pnpm-lock.yaml

closes  #6
```bash
cd backend
```
```bash
```

feat: Create service logic

---

backend/backend/settings.py
backend/zane_api/views/projects.py
backend/zane_api/views/serializers.py
frontend/src/api/v1.ts
frontend/src/components/service-cards.tsx
openapi/schema.yml

When we deploy, we should have a deploying status to inform the users that a deployment is in progress.
```bash
cd backend
```
```bash
```

✨ add `DEPLOYING` service status

---

backend/zane_api/urls.py
backend/zane_api/views/logs.py
backend/zane_api/views/serializers.py
frontend/index.html

In this PR, I added a new API endpoint to see the logs sent to the proxy, for debugging.
```bash
cd backend
```
```bash
```

Add Proxy HTTP logs endpoint

---

frontend/src/api/v1.ts
openapi/schema.yml

> Same as the title
```bash
cd backend
```
```bash
```

:memo: fix missing openapi file

---

backend/zane_api/tests/deployment.py
backend/zane_api/views/serializers.py

This PR adds a restriction to only allow volumes mounted to a host in `READ_ONLY` mode. This is because I've noticed that host volumes are almost always used only for read only usages (ex: `/var/run/docker.sock` or `/etc/localtime`), and it will make it easier for the future feature of multiple environments (preview and other), since in them we would need to duplicate the service and its volumes, allowing read-write volumes could cause race condition errors when two services write to the same volume.
```bash
cd backend
```
```bash
```

:recycle: Restrict host volumes to `READ_ONLY` mode

---

deploy.mk

I forgot to fix this issue in #210 
```bash
cd backend
```
```bash
```

🔧 fix makefile syntax error

---

deploy.mk

Fix syntax.
```bash
cd backend
```
```bash
```

🔧 fix makefile syntax

---

docker/docker-stack.prod-temporal-ui.yaml

Like the title
```bash
cd backend
```
```bash
```

🔧 move temporal-ui stack to its own file

---

docker/docker-stack.prod.yaml
docker/docker-stack.yaml

Some binaries for the image where not build correctly, see : https://github.com/temporalio/temporal/issues/6146
```bash
cd backend
```
```bash
```

⬆️ upgrade `temporal-admin-tools` image because it was not built correctly

---

backend/zane_api/temporal/worker.py

We won't use the `default` namespace, instead the namespace defined in `settings.py`
```bash
cd backend
```
```bash
```

🐛 Use the correct temporalio namespace for the worker

---

frontend/src/routes/_dashboard/index.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/index.tsx
frontend/src/utils.ts

Some UI changes :
- We include number of days in `timeElapsed` formatter to fix issues like this 
- We also do not show pagination if number of items is less than 10, in deployments & projects page  
```bash
cd backend
```
```bash
```

Refactor : some UI changes

---

.vscode/settings.json
docs/public/robots.txt
docs/src/content/docs/index.mdx
frontend/src/routes/_dashboard.lazy.tsx

The previous one had not the correct link.
```bash
cd backend
```
```bash
```

🔍 use the correct link for sitemap

---

backend/zane_api/temporal/activities.py

Added new headers sent from zaneops : 
- `x-zane-dpl-hash` : the current deployment hash in production
- `x-zane-dpl-slot` : the current slot for the deployment in production
```bash
cd backend
```
```bash
```

♻️ send zane headers for debugging the current deployment in production.

---

frontend/src/api/v1.ts
frontend/src/lib/hooks/use-deploy-docker-service-mutation.ts
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.lazy.tsx

In this PR, we added the logic to handle the environment variables in the UI.
```bash
cd backend
```
```bash
```

Feat: env variables UI logic

---

frontend/package.json
frontend/src/components/code.tsx
frontend/src/components/deployment-cards.tsx
frontend/src/components/ui/accordion.tsx
frontend/src/components/ui/alert.tsx
frontend/src/components/ui/button.tsx
frontend/src/components/ui/checkbox.tsx
frontend/src/components/ui/select.tsx
frontend/src/components/ui/switch.tsx
frontend/src/index.css
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.lazy.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx
frontend/src/routes/_dashboard/project_/$slug_.create-service.docker.lazy.tsx
frontend/tailwind.config.js
pnpm-lock.yaml

The UI for the settings for the service details where the user can change all the configurations for a service.
```bash
cd backend
```
```bash
```

Feat: service details settings page UI

---

frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.lazy.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx

Some littles fixes that I noticed.
```bash
cd backend
```
```bash
```

some UI fixes for the service settings page

---

backend/zane_api/models/base.py
backend/zane_api/tests/deployment.py
frontend/src/lib/hooks/use-request-service-change-mutation.ts
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.lazy.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx

> exactly as the title says
```bash
cd backend
```
```bash
```

feat: update service ports

---

backend/zane_api/temporal/activities.py
backend/zane_api/validators.py
backend/zane_api/views/serializers.py
frontend/src/components/ui/accordion.tsx
frontend/src/lib/utils.ts
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx

UI for the service urls settings.
```bash
cd backend
```
```bash
```

feat: update service urls UI

---

backend/zane_api/serializers.py
backend/zane_api/views/serializers.py
frontend/src/components/ui/select.tsx
frontend/src/index.css
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.lazy.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx

The UI for the command & healthcheck for a service settings.
```bash
cd backend
```
```bash
```

feat: update command & healthcheck

---

backend/zane_api/views/proxy.py
backend/zane_api/views/serializers.py
frontend/src/components/ui/accordion.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.lazy.tsx
frontend/src/utils.ts

```bash
cd backend
```
```bash
```

feat: volumes service UI logic

---

frontend/src/components/ui/sonner.tsx

So that it follows the design system.
```bash
cd backend
```
```bash
```

💄 use primary color for the toast

---

README.md
docs/astro.config.mjs
docs/public/robots.txt
docs/src/content/docs/screenshots.mdx
docs/src/pages/api-reference/openapi.astro
frontend/src/routes/_dashboard.lazy.tsx

Instead of accessing the docs using `/docs`, we can access the docs directly with `/`
```bash
cd backend
```
```bash
```

♻️ move zaneops docs to the root

---

Dockerfile.docs
docs/Caddyfile

exactly as the title says. 
```bash
cd backend
```
```bash
```

🐛 copy the assets from the correct folder in docker for the docs

---

backend/zane_api/views/serializers.py
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.lazy.tsx

exactly as the PR title says.
```bash
cd backend
```
```bash
```

♻️ allow for empty values for env variables

---

deploy.mk
docs/src/content/docs/get-started.mdx

Yeah
```bash
cd backend
```
```bash
```

🐛 fix typo in deploy makefile (again)

---

deploy.mk

exactly as the tilte.
```bash
cd backend
```
```bash
```

🐛 escape make deploy so that it isn't interpreted as a command

---

frontend/src/components/status-badge.tsx
frontend/src/index.css
frontend/src/lib/queries.ts
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug.lazy.tsx
frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash.lazy.tsx
frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/details.lazy.tsx
frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/http-logs.tsx
frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/index.tsx
frontend/src/utils.ts
frontend/tailwind.config.js

The Layout for when we click on a deployment.
- a production deployment with a URL
- a removed deployment
- a failed deployment
```bash
cd backend
```
```bash
```

feat: Deployment details Layout

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/refactor.md
.github/pull_request_template.md

Simplified issues & PR templates.
> [!WARNING]
```bash
cd backend
```
```bash
```

chore: update issue & pull request templates

---

frontend/src/main.tsx
frontend/src/routes/_dashboard.tsx
frontend/src/routes/_dashboard/create-project.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/env-variables.tsx
frontend/src/routes/_dashboard/project_/$project_slug.services.docker.$service_slug/settings.tsx
frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash.tsx
frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/details.tsx
frontend/src/routes/_dashboard/project_/$slug.create-service.tsx
frontend/src/routes/_dashboard/project_/$slug_.create-service.docker.tsx
frontend/src/routes/login.tsx
frontend/vite.config.ts

Exactly as the title says.
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: auto-code splitting and pending UI in tanstack router

---

backend/backend/bootstrap.py

forgot to do this.
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: rename `502` page title

---

frontend-new/app/lib/constants.ts
frontend-new/app/lib/queries.ts
frontend-new/app/root.tsx
frontend-new/app/routes/deployments/deployment-details.tsx
frontend-new/app/routes/deployments/deployment-http-logs.tsx
frontend-new/app/routes/deployments/deployment-logs.tsx
frontend-new/app/routes/layouts/deployment-layout.tsx
frontend-new/app/routes/layouts/service-layout.tsx
frontend-new/package.json
frontend-new/tsconfig.json
frontend/src/routes/_dashboard/project_/$project_slug_.services.docker.$service_slug.deployments.$deployment_hash/index.tsx
pnpm-lock.yaml

Final part of the rewrite to react router v7, attacking the deployment logs page.
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: move to react router final part : deployment logs page

---

frontend/app/routes/layouts/dashboard-layout.tsx

Some UI fixes regarding the command input in the search bar : 
- the margin of the input was uneven :
**before :** 
**after :** 
- the command menu was below the logs view when the logs view was expanded :  
**before :** 
**after :** 
> [!WARNING]
```bash
cd backend
```
```bash
```

💄 some ui fixes

---

docker/proxy/Dockerfile

For debugging purposes in production.
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: install `jq` in `proxy` image

---

backend/zane_api/views/serializers.py
frontend/app/api/v1.ts
frontend/app/components/http-log-request-details.tsx
frontend/app/components/ui/button.tsx
frontend/app/lib/constants.ts
frontend/app/lib/queries.ts
frontend/app/routes/dashboard.tsx
frontend/app/routes/deployments/deployment-http-logs.tsx
frontend/app/routes/services/service-http-logs.tsx
frontend/app/routes/services/settings/service-resource-limits-form.tsx
openapi/schema.yml

I made some improvements to the user experience : 
- Use `0xx` status in the front to filter by status types 
- I removed archived projects from the UI as they are not really used
- I added icons to indicate the sorting order in the project list 
> [!WARNING]
```bash
cd backend
```
```bash
```

feat: some ui improvements

---

backend/zane_api/management/commands/create_system_cleanup_schedule.py
docker/docker-compose.yaml

This job is not necessary on dev as it could cleanup the docker containers on a maintainers machine (probably not something they want).
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: do not run system cleanup job in dev

---

backend/zane_api/management/commands/create_system_cleanup_schedule.py

It would break production.
> [!WARNING]
```bash
cd backend
```
```bash
```

fix: revert updating schedule id

---

backend/search/client.py

Add retries and more timeout for longer queries, since we noticed it on production. 
> [!WARNING]
```bash
cd backend
```
```bash
```

fix: increase elasticsearch timeouts and add retries

---

frontend/app/routes/services/services-env-variables.tsx

This : 
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: add icon on `env` button

---

README.md
backend/backend/settings.py
backend/zane_api/temporal/activities.py
backend/zane_api/temporal/schedules/activities.py
backend/zane_api/temporal/schedules/workflows.py
backend/zane_api/temporal/workflows.py
backend/zane_api/tests/create_resources_for_deployment.py
backend/zane_api/tests/deployment.py
backend/zane_api/tests/more_deployments.py
backend/zane_api/views/projects.py
backend/zane_api/views/serializers.py
deploy.mk
frontend/app/api/v1.ts
frontend/app/components/service-cards.tsx
frontend/app/routes/layouts/dashboard-layout.tsx
frontend/app/routes/login.tsx
frontend/app/routes/services/settings/service-deploy-url-form.tsx
frontend/app/routes/services/settings/service-ports-form.tsx
frontend/app/routes/services/settings/service-urls-form.tsx
frontend/app/routes/services/settings/service-volumes-form.tsx
openapi/schema.yml

Some stuff I missed : 
- Bugs regarding deployments : some deployment would show an invalid status after the deployment has finished, probably because of a race condition with the monitor health check, so we delete the schedule before launching a new deployment and also we prevent `SLEEPING` and `REMOVED` services from being checked 
- Reducing the occurence at which the metrics collection run from 5s intervals to 30s because it would block the monitor job in certain cases
- Some other bugs (check commits)
> [!WARNING]
```bash
cd backend
```
```bash
pnpm install --frozen-lockfile # Install …
```

fix: some fixes before v1 

---

frontend/app/components/service-cards.tsx
frontend/app/components/ui/alert.tsx

some ui fixes
> [!WARNING]
```bash
cd backend
```
```bash
```

fix: some minor UI tweaks

---

README.md

as the title says.
> [!WARNING]
```bash
cd backend
```
```bash
```

chore: add product hunt embed

---

README.md

as the title says.
> [!WARNING]
```bash
cd backend
```
```bash
```

fix: link to installation steps in the readme

---

frontend/app/components/ui/command.tsx
frontend/app/components/ui/input.tsx
frontend/app/components/ui/textarea.tsx
frontend/app/lib/utils.ts
frontend/app/routes/layouts/dashboard-layout.tsx
frontend/app/routes/login.tsx
frontend/app/routes/projects/create-project.tsx
frontend/app/routes/projects/project-settings.tsx
frontend/app/routes/services/archive-service.tsx
frontend/app/routes/services/create-docker-service.tsx
frontend/app/routes/services/services-env-variables.tsx
frontend/app/routes/services/settings/service-danger-zone-form.tsx

In this PR, I made some nice user experience changes : 
- Made the `DEV` overlay way bigger to be more visible since I kept missing it :
-  Added confirmation dialogs for when archiving a service or a project, with the title renamed to `delete` to be more direct :  
- Added different style in the `<Input>` component for when it is invalid :  
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: Some user experience changes

---

.github/workflows/build-push-images-tag.yaml

Please provide a brief summary of the changes. If it fixes a bug or resolves a feature request, be sure to link to that issue.
fixes #
> [!WARNING]
```bash
cd backend
```
```bash
```

fix: revert changes made to release pipeline

---

deploy.mk

These are fixes regarding the `Makefile`.
> [!WARNING]
```bash
cd backend
```
```bash
```

fix: include `loki-config` in setup and fix `delete` script

---

backend/zane_api/temporal/activities.py
backend/zane_api/utils.py

explained here : https://github.com/zane-ops/zane-ops/blob/0f7873fc780404d37636ad6cad334014d405c644/backend/zane_api/temporal/activities.py#L593-L604
> [!WARNING]
```bash
cd backend
```
```bash
```

🩹 workaround for `502 Bad Gateway` error

---

frontend/app/routes/services/settings/service-healthcheck-form.tsx

A simple PR.
> [!WARNING]
```bash
cd backend
```
```bash
```

chore: add link to docs in health check

---

frontend/app/routes/onboarding.tsx

Add password confirmation and a message for creating the first user.
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: add password confirmation to onboarding page

---

frontend/app/api/v1.ts
frontend/app/components/ui/button.tsx
frontend/app/lib/queries.ts
frontend/app/routes.ts
frontend/app/routes/layouts/dashboard-layout.tsx
frontend/app/routes/trigger-update.tsx

Automatic Update UI
closes #402 
> [!WARNING]
```bash
cd backend
```
```bash
```

feat: automatic updates check (frontend)

---

frontend/app/routes/layouts/dashboard-layout.tsx
frontend/app/routes/trigger-update.tsx

Please provide a brief summary of the changes. If it fixes a bug or resolves a feature request, be sure to link to that issue.
fixes #
> [!WARNING]
```bash
cd backend
```
```bash
```

💄 hide the update modal after update request sent

---

backend/search/loki_client.py
backend/zane_api/temporal/activities/main_activities.py
backend/zane_api/temporal/shared.py
backend/zane_api/tests/base.py
backend/zane_api/tests/git_services.py
backend/zane_api/tests/logs.py
backend/zane_api/views/helpers.py
frontend/app/components/deployment-cards.tsx
frontend/app/components/service-cards.tsx
frontend/app/lib/queries.ts
frontend/app/routes/deployments/deployment-logs.tsx
frontend/app/routes/layouts/deployment-layout.tsx
frontend/app/routes/layouts/service-layout.tsx
frontend/app/routes/services/create-service.tsx
frontend/app/routes/services/settings/service-builder-form.tsx
frontend/app/routes/services/settings/service-git-source-form.tsx

In this PR, we fixed a lof of bugs regarding #422 :
- fixed a bug when redeploying old service with a different value for `builder` not being applied
- fixed a bug with infinite logs not skipping some logs and not being cached correctly
- fixed a bug in the archive activity, instead of scaling services to `0` and waiting for docker tasks for the service to be removed, we directly remove the service and instead wait for all its containers to be removed
- Attempted to add a fix to a rare random bug happening when you deploy services and the previous service not being marked as `REMOVED` even though it was effectively removed
> [!WARNING]
```bash
cd backend
pnpm run freeze # …
```

fix: Some bug fixes

---

docker/app/Dockerfile

It's something I missed in the previous PR
> [!WARNING]
```bash
cd backend
```
```bash
```

🐛 install `git` in production Dockerfile

---

backend/zane_api/tests/more_deployments.py
backend/zane_api/views/deployments.py
frontend/app/api/v1.ts
frontend/app/components/deployment-cards.tsx
frontend/app/components/service-cards.tsx
frontend/app/routes/deployments/deployment-details.tsx
frontend/app/routes/services/settings/service-deploy-url-form.tsx
openapi/schema.yml

**Some fixes in the UI regarding git services:** 
- The branch name wouldn't show in one line, we fixed it
- We made it so that only the first line of the commit message is shown in the deployment card 
-  We added the full commit message in the deployment details page :
- The deploy webhook URL shown in the UI was completly wrong, it should have shown `git` in the path name
**Other changes:**
- The deploy webhook URL now returns `202 accepted` with an empty response instead of `200 OK` with the deployment data, this way if it is used inside of Github Actions with curl, the output will be empty and not leak potentially private data (ex: env variables)
---
> [!WARNING]
```bash
cd backend
pnpm run openapi # will generate OpenAPI schema at …
```

fix: Some UI fixes

---

backend/zane_api/models/base.py
backend/zane_api/process.py
backend/zane_api/temporal/activities/git_activities.py
backend/zane_api/temporal/helpers.py
backend/zane_api/temporal/shared.py
backend/zane_api/temporal/workflows.py
backend/zane_api/tests/base.py
backend/zane_api/tests/git_services.py
frontend/app/routes/layouts/deployment-layout.tsx
frontend/app/routes/services/settings/services-settings.tsx

The build process wasn't connecting to the network of the environment in which the service is in, so this PR fixes it, this is done by adding `network=host` to the `buildx` process. 
However this doesn't work with railpack, so we instead used a workaround where we replace all occurences of network aliases of other services with their IPs in environment variables. I opened an issue for that in railpack repository : https://github.com/railwayapp/railpack/issues/145
**Other changes :**
- We fixed the process termination step to gracefully cancel  & terminate the docker build process without resulting in zombie processes
- We added `FORCE_COLOR` for all docker build operations by default
- we made it so that on the frontend, if you are on the deployment page, the current status of the …

fix: connect build process to the environment network

---

.github/pull_request_template.md
.github/workflows/build-push-images-canary.yaml
.github/workflows/build-push-images-dev.yaml
.github/workflows/build-push-images-tag.yaml
Makefile
backend/.dockerignore
backend/Dockerfile
backend/package.json
backend/webshell/consumers.py
docker/docker-compose.yaml
frontend/app/root.tsx
frontend/vite.config.ts

- Updated the CI to use `slim.Dockerfile` in production too
- Fixed ptys not being closed on terminals to deployments when the user is disconnected without typing `exit`
- Made it so that react query cache is only persisted in production
> [!WARNING]
```bash
cd backend
```
```bash
```

♻️ use slim `Dockerfile` for production builds too

---

backend/zane_api/views/projects.py
frontend/app/routes/settings/create-github-app.tsx

- As said in the title, we should allow specifying the redirect & webhook URI. I wanted to cover this use-case because in my homelab, I cannot expose the base URL, i have to use another proxy for the webhook
- I also made it so that the org is a checkbox, if the org is shown the user might think it's a required field
| New form |  With org checked |
| ------------ | ------------ |
| <img width="780" height="436" alt="image" src="https://github.com/user-attachments/assets/d82ee6d8-8466-4f07-82e6-a15a34bd4556" />    | <img width="867" height="505" alt="image" src="https://github.com/user-attachments/assets/152d70f1-ae9a-4447-91be-12ec86ed961a" />  |
> [!WARNING]
```bash
cd backend
pnpm run openapi # will generate OpenAPI schema at …
```

feat: allow specifying a redirect URI when creating github app

---

frontend/app/routes/services/create-private-git-service.tsx
frontend/app/routes/services/create-service.tsx

Make the text in the service creation clearer for users.
| Before | After |
| ------------ | ------------ |
| <img width="461" height="377" alt="image" src="https://github.com/user-attachments/assets/a00a2918-b202-4c30-ade1-c82e4e05b808" />     | <img width="516" height="408" alt="image" src="https://github.com/user-attachments/assets/1d8130c1-df21-4cd3-a2c7-8be52277f937" />   |
> [!WARNING]
```bash
cd backend
```
```bash
```

chore: make button labels more accurate

---

frontend/app/routes/services/create-private-git-service.tsx
frontend/app/routes/services/create-public-git-service.tsx
frontend/app/routes/services/create-service.tsx

I messed up in #484 
I also tidied up a little the **new Git service** page UI.
> [!WARNING]
```bash
cd backend
```
```bash
```

refactor: reorder links again 🤦🏾‍♂️

---

frontend/app/routes/services/create-git-service-from-gitapp.tsx
frontend/app/routes/services/create-private-git-service.tsx
frontend/app/routes/services/create-public-git-service.tsx

...
> [!WARNING]
```bash
cd backend
```
```bash
```

chore: some UI refactors

---

frontend/app/routes/services/create-git-service-from-gitapp.tsx

I messed up in #487 again 🤦🏾 
> [!WARNING]
```bash
cd backend
```
```bash
```

fix: Some fixes
